version: '3.8'
services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile  # Dockerfile para el backend
    ports:
      - "3001:3001"
    networks:
      - mynetwork

  public:
    build:
      context: .
      dockerfile: public/Dockerfile  # Dockerfile para el frontend
    ports:
      - "80:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
